config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'

  resources :articles

  devise_for :users

  get 'about' => 'welcome/about'

  resources :users, only: [:update]

end

app/models/article.rb
class Article < ActiveRecord::Base
  belongs_to :user

  validates :title, length: { minimum: 5 }, presence: true
  validates :body, length: { minimum: 20 }, presence: true

end

app/models/user.rb
class User < ActiveRecord::Base

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :confirmable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  attr_accessor :login

  # validates_format_of :username, with: /^[a-zA-Z0-9_\.]*$/, :multiline => true

  def avatar_url(size)
    gravatar_id = Digest::MD5::hexdigest(self.email).downcase
    "http://gravatar.com/avatar/#{gravatar_id}.png?s=#{size}"
  end

  def self.find_first_by_auth_conditions(warden_conditions)
    conditions = warden_conditions.dup
    if login = conditions.delete(:login)
      where(conditions).where(["lower(username) = :value OR lower(email) = :value", { :value => login.downcase }]).first
    else
      if conditions[:username].nil?
        where(conditions).first
      else
        where(username: conditions[:username]).first
      end
    end
  end

  def send_devise_notification(notification, *args)
    devise_mailer.send(notification, self, *args).deliver_later
  end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pundit
  protect_from_forgery with: :exception
  # before_action :authenticate_user!
  before_filter :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    added_attrs = [:username, :email, :password, :password_confirmation, :remember_me]
    devise_parameter_sanitizer.permit :sign_up, keys: added_attrs
    devise_parameter_sanitizer.permit :account_update, keys: added_attrs
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

  def index
    @articles = Article.all
  end

  def show
    @article = Article.find(params[:id])
  end

  def edit
    @article = authorize Article.find(params[:id])
    # authorize @article, :update?
  end

  def new
    @article = Article.new
  end

  def create
    @article =  authorize Article.new(article_params)
    # @article.user = current_user

    if @article.save
      flash[:notice] = "Article was saved successfully."
      redirect_to @article
    else
      flash.now[:alert] = "There was an error saving this article. Please try again."
      render :new
    end
  end

  def update
    @article = authorize Article.find(params[:id])
    # @article.assign_attributes(article_params)
    # authorize @article

    if @article.update(article_params)
      flash[:notice] = "Article was updated successfully."
      redirect_to [@article]
    else
      flash.now[:alert] = "There was an error saving this article. Please try again."
      render :edit
    end
  end

  def destroy
    @article = authorize Article.find(params[:id])
    # authorize @article, :update?
    if @article.destroy
      flash[:notice] = "\"#{@article.title}\" was deleted successfully."
      redirect_to action: :index
    else
      flash.now[:alert] = "There was an error deleting this article."
      render :show
    end
  end

  private
  def article_params
    params.require(:article).permit(:title, :body)
  end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def form_group_tag(errors, &block)
  css_class = 'form_group'
  css_class << 'has-error' if errors.any?
  content_tag :div, capture(&block), class: css_class
end
end

app/helpers/articles_helper.rb
module ArticlesHelper
  # def user_is_authorized_for_article?(article)
  #   current_user && (current_user == article.user)
  #   # current_user && (current_user == article.user || current_user.admin?)
  # end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/articles/_form.html.erb
<div class="row">
  <div class="col-md-4">
    <p>Guidelines to remember:</p>
    <ul>
      <li>Try not to lie too much.</li>
      <li>Exaggeration is expected.</li>
      <li>Type as fast as you can.</li>
    </ul>
  </div>
</div>

<%= form_for [@article] do |f| %>
  <% if @article.errors.any? %>
    <div class="alert alert-danger">
      <h4><%= pluralize(@article.errors.count, "error") %>.</h4>
      <ul>
        <% @article.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%= form_group_tag(@article.errors[:title]) do %>
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control', placeholder: "Enter article title" %>
  <% end %>

  <%= form_group_tag(@article.errors[:body]) do %>
    <%= f.label :body %>
    <%= f.text_area :body, rows: 8, class: 'form-control', placeholder: "Ender article body" %>
  <% end %>

  <div class="form-group">
    <%= f.submit "Save", class: 'btn btn-success' %>
  </div>
<% end %>

app/views/articles/edit.html.erb
<h1>Edit Article</h1>
<div class="col-md-8">
  <%= render partial: 'form' %>
</div>

app/views/articles/index.html.erb
<div class="row" style="margin-left: 20px;">
  <br />
  <div class="col-md-8">
    <% @articles.each do |article| %>
      <div class="media">
        <div class="media-body">
          <h4 class="media-heading">
            <%= link_to article.title, article %>
          </h4>
          <small>
            <%= article.body %>
          </small>
        </div>
      </div>
    <% end %>
  </div>
  <br />
  <div class="col-md-4">
    <% if user_signed_in? %>
      <%= link_to "New Article", new_article_path, class: 'btn btn-success' %>
    <% end %>
  </div>
</div>

app/views/articles/new.html.erb
<h1 class="name-heading" style="text-align:left;">New Article</h1>
<br />
<div class="col-md-8 form">
  <%= render partial: 'form' %>
</div>

app/views/articles/show.html.erb
<div>
  <h2 class="name-heading">
    <%= @article.title %> <br />
    <small>
      created <%= time_ago_in_words(@article.created_at) %> ago by <%=  %>
    </small>
    <br />
  </h2>
</div>
<br />
<div class="col-md-8">
  <p class="article-body"><%= simple_format(@article.body) %></p>
</div>
<div class="footer">
  <% if policy(@article).update? %>
    <%= link_to "Edit", edit_article_path(@article), class:'btn btn-success' %>
    <span class='spacer'></span>
    <%= link_to "Delete", [@article], method: :delete, class: 'btn btn-danger', data: {confirm: 'Are you suer you want to delete this article?'} %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Encyclospeedia</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div>
    <div class="container">
      <ul class="nav nav-tabs pull-left">
        <li><%= link_to "Home", root_path %></li>
        <div class="dropdown" style="float:right; padding: 10px;">
          <button class="btn btn-primary dropdown-toggle" type="button" data-toggle="dropdown">Articles
          <span class="caret"></span></button>
          <ul class="dropdown-menu">
            <li><%= link_to 'Horse', articles_path, :class => 'navbar-link' %></li>
            <li><%= link_to "Hound", articles_path, :class => 'navbar-link' %></li>
          </ul>
        </div>
      </ul>
      <ul class="nav nav-tabs pull-right">
        <% if user_signed_in? %>
          <div class="dropdown" style="float:right;">
            <button class="btn btn-primary dropdown-toggle" type="button" data-toggle="dropdown">Welcome, <strong><%= current_user.username %></strong>
            <span class="caret"></span></button>
            <ul class="dropdown-menu">
              <li><%= link_to 'Profile', user_path(current_user), :class => 'navbar-link' %></li>
              <li><%= link_to 'Edit Profile', edit_user_registration_path, :class => 'navbar-link' %></li>
              <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete, :class => 'navbar-link' %></li>
            </ul>
            <%= image_tag current_user.avatar_url(48), class: "gravatar" %>
          </div>
          <% else %>
            <li><%= link_to "Sign Up", new_user_registration_path, :class => 'nav ' %></li>
            <li><%= link_to "Sign In", new_user_session_path, :class => 'navbar-link' %></li>
          <% end %>
        </ul>
        <br />
  </div>

    <div class="flash">
      <% if flash[:notice] %>
        <div class="alert alert-success">
          <button type="button" class="close" data-dismiss="alert">&times;</button>
          <%= flash[:notice] %>
        </div>
      <% elsif flash.now[:alert] %>
      <div class="alert alert-danger">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <%= flash.now[:alert] %>
      </div>
      <% elsif flash[:alert] %>
        <div class="alert alert-warning">
          <button type="button" class="close" data-dismiss="alert">&times;</button>
          <%= flash[:alert] %>
        </div>
      <% end %>
    </div>
  <%= yield %>
  </div>
</body>
</html>

app/views/users/show.html.erb
<h1>Users#show</h1>
<p>Find me in app/views/users/show.html.erb</p>

app/views/welcome/about.html.erb
<h1>About Encyclo<i>speed</i>ia</h1>
<p>
  Find and learn about any possible topic!
  Can't find an article on your topic? Create one!
</p>

app/views/welcome/index.html.erb
<br  />

<div class="image">
  <div class="jumbotron">
    <div >
      <h1 style="padding-left: 20px;"><span>Encyclo<i>speed</i>ia</span></h1>
    </div>
    <div class="horse">
      <img src="http://www.freeiconspng.com/uploads/horse-png-5.png" style="max-width: 100%; height: 400px; padding-left: 50px;" />
    </div>
    <br />
    <p class="phrase" style="padding-left: 20px;">
      Find and learn about any possible topic!
      <br />
      Can't find an article on your topic? Create one!
    </p>
    <div class="points" style="margin-right: 30px;">
      <div class="row">
        <h2>Solves the Knowledge Crisis of Today!</h2>
        <p>Encyclospeedia is on a mission to close the Knowledge Gap!</p>
      </div>
      <div class="row">
        <h2>Eliminates Real Life Social Interaction!</h2>
        <p>Who needs a classroom when you have Encyclospeedia?</p>
      </div>
      <div class="row">
        <h2>Makes you a better person!</h2>
        <p>Learn everything you could ever know, even fictional stuff!</p>
      </div>
    </div>
  </div>
</div>